// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelExport() {
  return window['go']['main']['App']['CancelExport']();
}

export function CheckApiKey() {
  return window['go']['main']['App']['CheckApiKey']();
}

export function CheckDBConnection() {
  return window['go']['main']['App']['CheckDBConnection']();
}

export function ExportCSV() {
  return window['go']['main']['App']['ExportCSV']();
}

export function ExportSQL() {
  return window['go']['main']['App']['ExportSQL']();
}

export function GetSettingDir() {
  return window['go']['main']['App']['GetSettingDir']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function GetUserHomeDirectory() {
  return window['go']['main']['App']['GetUserHomeDirectory']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function ReadBuild() {
  return window['go']['main']['App']['ReadBuild']();
}

export function ReadExportStatus() {
  return window['go']['main']['App']['ReadExportStatus']();
}

export function ReadVersion() {
  return window['go']['main']['App']['ReadVersion']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectSettingsDirectory() {
  return window['go']['main']['App']['SelectSettingsDirectory']();
}

export function ValidateApiKey(arg1) {
  return window['go']['main']['App']['ValidateApiKey'](arg1);
}
