// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';
import {api} from '../models';

export function CheckApiKey():Promise<boolean>;

export function ExportCSV():Promise<void>;

export function ExportSQL():Promise<void>;

export function GetLatestVersion(arg1:string):Promise<update.ReleaseInfo>;

export function GetSettings():Promise<api.ExporterConfiguration>;

export function GetTemplates():Promise<Array<api.TemplateResponseItem>>;

export function GetUserHomeDirectory():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ReadBuild():Promise<string>;

export function ReadExportStatus():Promise<void>;

export function ReadVersion():Promise<string>;

export function SaveSettings(arg1:api.ExporterConfiguration):Promise<void>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectSettingsDirectory():Promise<void>;

export function ValidateApiKey(arg1:string):Promise<boolean>;
