// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckApiKey() {
  return window['go']['main']['App']['CheckApiKey']();
}

export function ExportCSV() {
  return window['go']['main']['App']['ExportCSV']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTemplates() {
  return window['go']['main']['App']['GetTemplates']();
}

export function GetUserHomeDirectory() {
  return window['go']['main']['App']['GetUserHomeDirectory']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ReadExportStatus() {
  return window['go']['main']['App']['ReadExportStatus']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function ValidateApiKey(arg1) {
  return window['go']['main']['App']['ValidateApiKey'](arg1);
}
