# yamllint disable rule:line-length
---
name: package

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main


jobs:
  package:
      strategy:
        matrix:
          go-version: [1.18]
          node-version: [16]
          os: [ubuntu-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Install Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go-version }}

        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install linux dependencies
          if: matrix.os == 'ubuntu-latest'
          run: sudo apt-get update -y && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev build-essential pkg-config

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install wails
          run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

        - name: Build package windows
          if: matrix.os == 'ubuntu-latest'
          run: |
            export PATH=$PATH:$(go env GOPATH)/bin
            echo "building on ${{ matrix.os }}"
            echo ${{ env.GITHUB_REF }}
            echo ${{ env.GITHUB_HEAD_REF }}
            ./scripts/build-windows.sh

        - name: release
          uses: softprops/action-gh-release@v1
          with:
            files: |
                build/bin/macos/exporter-darwin-amd64.zip
                build/bin/macos/exporter-darwin-arm64.zip
                build/bin/linux/exporter.tar.gz
                exporter-windows.tar.gz